### ISSUE TITLE
请问为什么要对\0进行替换

### ISSUE THREAD

**Issue by Lutl** [yuehuTi/upvmap#4]
我对tsv读取的过程中，会跳出来转码错误的问题，这和对\0的替换有关系吗？求教

**Comment by yuehuTi** [comment]
有agent跟我说他的数据没跑出来，我看了下他收到的数据，里很多行数据不完整且被0x00大量填充，所以针对这个情况对0x00进行了特殊处理

**Comment by Lutl** [comment]
可能是下午敲代码给敲蒙了，刚才重写了一遍就好了，都不知道转码怎么错的。谢谢你指点啦
